### ISSUE TITLE
Config should be published in Statamic subfolder of config folder

### ISSUE THREAD

**Issue by jimblue** [HandmadeWeb/statamic-cloudflare#1]
https://github.com/HandmadeWeb/statamic-cloudflare/blob/976b9118e223ef83a88b3629a0c8e2c976fe6184/src/ServiceProvider.php#L53

Here is my suggestion, to improve the config naming in Artisan and the destination of the published config :

```php
$this->mergeConfigFrom(__DIR__ . '/../config/config.php', 'cloudflare');

if ($this->app->runningInConsole()) {
    $this->publishes([
        __DIR__ . '/../config/config.php' => config_path('statamic/cloudflare.php'),
    ], 'cloudflare-config');
}
```

**Comment by michaelr0** [comment]
Hi @jimblue, thanks for the suggestion, I had initially considered nesting it under the Statamic folder but decided not to, at least under the idea that perhaps that folder should be reserved for Statamic core config files, I also had a brief look at how some other Statamic addon's are handling it and I think I'm going to leave it as is.

**Comment by jimblue** [comment]
Hi @michaelr0,
You're welcome :)
About your decision, my 2 cents :
Most addons and even Statamic team addons config files are saved under `config/statamic`.
In my opinion this make more cents as it's Statamic addons, not Laravel addon.

**Comment by michaelr0** [comment]
Hi @jimblue,

Thanks, I had looked into it and based my decision around how some other add-on's had been handling it, now I understand it could go either way, however my decision was based on how the following have handled the location of the config file.

https://github.com/jonassiewertsen/statamic-butik
https://github.com/doublethreedigital/runway
https://github.com/doublethreedigital/simple-commerce
https://github.com/doublethreedigital/duplicator
https://github.com/WithCandour/statamic-aardvark-seo

At this stage, I don't want to change the location/name of the file, because it is likely to introduce issues for anyone that has already configured their settings and would be a breaking change, just to account for a naming preference.

Thanks :)

**Comment by jimblue** [comment]
Sure totaly understand you point, no worries 😉 
Thank you for taking the time to answer.
Peace ✌🏼

**Comment by michaelr0** [comment]
Not a problem, let us know should you find any issues :)
